apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-static-kube
  name: test-static-kube
  namespace: web-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-static-kube
  template:
    metadata:
      labels:
        app: test-static-kube
    spec:
      containers:
        - image: poulavbiswas/test-static-kube:latest
          name: test-static-kube
          ports:
            - containerPort: 5000
